from app.models import db, Post, environment, SCHEMA

def seed_posts():
    post1 = Post(name='Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=20.99,image="https://www.forkknifeswoon.com/wp-content/uploads/2014/10/simple-homemade-chicken-ramen-fork-knife-swoon-01.jpg",shop_id=1)
    post2 = Post(name='Shoyo Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=2.99,image="https://www.elmundoeats.com/wp-content/uploads/2021/02/FP-Quick-30-minutes-chicken-ramen.jpg",shop_id=1)
    post3 = Post(name='Shroom Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://pinchofyum.com/wp-content/uploads/Quick-Homemade-Ramen-Square.png",shop_id=1)
    post4 = Post(name='Chiken Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=20.25,image="https://assets.bonappetit.com/photos/5e3c7a3c866b940008106763/6:9/w_2320,h_3480,c_limit/HLY-Veggie-Ramen-16x9.jpg",shop_id=1)
    post5 = Post(name='Soy Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=20.49,image="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/190208-delish-ramen-horizontal-093-1550096715.jpg",shop_id=1)
    post6 = Post(name='Vegan Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29_1.jpg/1200px-Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29_1.jpg",shop_id=1)
    post7 = Post(name='Spicy Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=20.99,image="https://glebekitchen.com/wp-content/uploads/2017/04/tonkotsuramenfront.jpg",shop_id=1)
    post8 = Post(name='Beef Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=20.49,image="https://www.halfbakedharvest.com/wp-content/uploads/2021/10/Easy-Ginger-Chicken-and-Spinach-Ramen-1.jpg",shop_id=1)
    post9 = Post(name='Hot Chili Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=1, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.piesandtacos.com/wp-content/uploads/2020/12/galaxy-macarons-2-500x500.jpg",shop_id=1)
    post10 = Post(name='Purple Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.foodnetwork.com/content/dam/images/food/fullset/2014/4/11/0/FNM_050114-French-Macaroons-Recipe_s4x3.jpg",shop_id=2)
    post11 = Post(name='Gree Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.thetipsymacaron.com/wp-content/uploads/cotton-candy-macarons.jpg",shop_id=2)
    post12 = Post(name='Blue Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.wilton.com/dw/image/v2/AAWA_PRD/on/demandware.static/-/Sites-wilton-project-master/default/dwdcf97dc4/images/project/WLPROJ-9063/MeMaHa_39783%205.jpg",shop_id=2)
    post13 = Post(name='Red Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://brokenovenbaking.com/wp-content/uploads/2021/08/rainbow-macarons-19.jpg",shop_id=2)
    post14 = Post(name='Yellow Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://recipesblob.oetker.com/files/96b1ad47326547e0aed40738682b5e3e/9e07971e896b475c9e1cdbf635dcc6f9/750x910/raiinbow-macaron-2.jpg",shop_id=2)
    post15 = Post(name='Orange Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://littlesunnykitchen.com/wp-content/uploads/2021/12/Christmas-Macarons-Peppermint-1.jpg",shop_id=2)
    post16 = Post(name='Black Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.bigbearswife.com/wp-content/uploads/2018/03/Blue-Raspberry-Macarons-7-720x540.jpg",shop_id=2)
    post17 = Post(name='White Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=2, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://images.squarespace-cdn.com/content/v1/54151d7ee4b0a43a90459ae2/1600743669497-K2E8VHORQLKVTXV7FA0L/shutterstock_1115170646.jpg",shop_id=2)
    post18 = Post(name='Birria Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=3, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.billyparisi.com/wp-content/uploads/2021/04/birria-tacos-1.jpg",shop_id=3)
    post19 = Post(name='Meat Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=3, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.pressurecookrecipes.com/wp-content/uploads/2021/01/instant-pot-birria.jpg",shop_id=3)
    post20 = Post(name='Lamb Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=3, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://cookswellwithothers.com/wp-content/uploads/2021/11/IMG_6579.jpg",shop_id=3)
    post21 = Post(name='Steak Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=3, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://i0.wp.com/images.303magazine.com/uploads/2021/02/65303524_687399341696805_6237402028398608384_o.jpg",shop_id=3)
    post22 = Post(name="Zesty Tofu Stir-Fry with Peanuts -Cilantro Creamy Parmesan- Risotto with Roasted Vegetables",user_id=4,price=22.23,image="https://photogenicfood.files.wordpress.com/2013/02/20130206-103124.jpg?w=618",description="Juicy, seasoned grilled steak with a crispy crust and tender center, Fluffy, buttery croissants with layers of flaky pastry",shop_id="4")
    post23 = Post(name="Spicy Jalapeno -Lime Grilled Chicken -Savory Mushroom Leek Quiche -with a Whole Wheat Crust",user_id=4,price=12.21,image="https://www.2foodtrippers.com/wp-content/uploads/2019/07/Norway-Food-Vafler-Waffle-with-Brunost-200x200.jpg",description="Warm, comforting bowl of chicken noodle soup with tender vegetables, Creamy, rich alfredo pasta with garlic and parmesan",shop_id=4)
    post24 = Post(name="Sweet Sour Pineapple- Chicken Fried- RiceHearty Lentil -Kale Soup with Smoked Paprika",user_id=4,price=7.55,image="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Good_Food_always_comes_in_small_doses..._%284006883441%29.jpg/1200px-Good_Food_always_comes_in_small_doses..._%284006883441%29.jpg",description="Spicy, tangy buffalo wings with a cool blue cheese dip, Tender, slow-cooked pulled pork with a smoky BBQ sauce",shop_id=4)
    post25 = Post(name="Crispy Sweet Potato -Black Bean Tacos with Avocado- CremaRich Creamy -Lobster Bisque with Sherry Thyme",user_id=4,price=6.99,image="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=4)
    post26 = Post(name="Smoky BBQ Pulled Pork -Sandwiches with Coleslaw- Fresh Bright Watermelon -Feta Salad with Mint Lime",user_id=4,price=5.99,image="https://images.immediate.co.uk/production/volatile/sites/30/2020/08/palestinian-food-29ad2b5.jpg?quality=90&resize=200,200",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=4)
    post27 = Post(name="Chunky Minestrone Soup -with Italian Sausage -Rosemary Crunchy Panko-Crusted Cod with",user_id=4,price=6.25,image="https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTB8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=4)
    post28 = Post(name="Hearty Lentil Kale Soup- with Smoked Paprika -Creamy Garlic -Parmesan Mashed Potatoes",user_id=4,price=9.99,image="https://cheflolaskitchen.com/wp-content/uploads/2021/02/DSC0353-Fufu-01292021-west-african-fufu-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=4)
    post29 = Post(name="Crispy Sweet Potato Black- Bean Tacos with Avocado Crema -Spicy Korean-style Fried Chicken with Gochujang Glaze",user_id=5,price=5.25,image="https://www.2foodtrippers.com/wp-content/uploads/2022/02/Jamon-Plate-at-Bar-Canete-in-New-Orleans-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post30 = Post(name="Rich Creamy Lobster Bisque- with Sherry Thyme and- Hearty Beef Vegetable- Stew with Guinness Thyme",user_id=5,price=3.99,image="https://www.curiouscuisiniere.com/wp-content/uploads/2021/08/Kunahi-Strukli.feature-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post31 = Post(name="Smoky BBQ Pulled Pork Sandwiches -with Coleslaw Crispy Air-Fried Eggplant Parmesan with- Mozzarella Basil",user_id=5,price=2.99,image="https://upload.wikimedia.org/wikipedia/commons/e/e2/Food_nutrition.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post32 = Post(name="Fresh Bright Watermelon -Feta Salad with Mint -Lime Fresh Fruity Raspberry-Blueberry Cheesecake Bars",user_id=5,price=4.99,image="https://tasteofmaroc.com/wp-content/uploads/2021/05/moroccan-orange-cake-1200w-opt-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post33 = Post(name="Zesty Quinoa Salad with -Pomegranate Vinaigrette Juicy -Grilled Pineapple- with Lime Glaze",user_id=5,price=12.99,image="https://www.plantbasedcooking.com/wp-content/uploads/2020/09/Vegetable-Noodle-Sou-with-Soy-Curls-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post34 = Post(name="Creamy Garlic Mushroom -Linguine Chewy -Sesame Noodles with -Peanut Sauce",user_id=5,price=12.25,image="https://omnivorescookbook.com/wp-content/uploads/2022/05/220503_Beef-And-Broccoli_550-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=5)
    post35 = Post(name="Spicy Tofu -Vegetable Stir Fry -Golden Fried Fish Tacos- with Cilantro Slaw",user_id=6,price=15.99,image="https://s3-media0.fl.yelpcdn.com/bphoto/pYaO-HEE47fhDTYKh1ojfw/258s.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=6)
    post36 = Post(name="Crispy Fried Chicken -with Honey Mustard -Sauce Savory Roasted -Eggplant with Garlic Parmesan",user_id=6,price=5.99,image="https://whereismyspoon.co/wp-content/uploads/2018/05/tres-leches-cake-13-1-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=6)
    post37 = Post(name="Loaded Baked Potato -with Sour Cream Chives- Creamy Lemon- Herb Risotto",user_id=6,price=7.99,image="https://www.curiouscuisiniere.com/wp-content/uploads/2022/08/alfajores-marplatenses-8.crop_-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=6)
    post38 = Post(name="Flaky Croissant with Melted- Brie Prosciutto Crunchy- Fried Green Tomatoes- with Ranch Dressing",user_id=6,price=15.99,image="https://burst.shopifycdn.com/photos/berry-cheesecake.jpg?width=1200&format=pjpg&exif=1&iptc=1",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=6)
    post39 = Post(name="Sizzling Grilled Steak- with Chimichurri -Hearty Vegetable -Bean Chili",user_id=7,price=19.99,image="https://amagicalmess.com/wp-content/uploads/2022/12/mermaid-bark-11-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=13)
    post40 = Post(name="Chilled Cucumber Dill -Soup Zesty- Lemon Herb- Grilled Chicken",user_id=7,price=11.99,image="https://numstheword.com/wp-content/uploads/2022/11/the-best-chocolate-pudding-cheesecake-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=13)
    post41 = Post(name="Smoky BBQ -Pulled Pork -Sandwich Smoky- Bacon Wrapped Meatloaf",user_id=7,price=9.99,image="https://www.lifebetweenthekitchenandthecoop.com/wp-content/uploads/Strawberry-Fluff-Dessert-325-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=13)
    post42 = Post(name="Warm Apple- Cinnamon Oatmeal- Warm Spiced- Apple Cider",user_id=7,price=16.99,image="https://foodgressing.com/wp-content/uploads/2017/08/mango-korean-shaved-dessert-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=13)
    post43 = Post(name="Tender beef brisket- with smoky BBQ -sauce Creamy pumpkin- risotto with sage parmesan",user_id=8,price=29.99,image="https://sucrecafe.com/wp-content/uploads/2020/01/img_9826-e1580256719133-1280x1280.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=14)
    post44 = Post(name="Spicy black -bean sweet potato- enchiladas Juicy grilled -pork chops with apple chutney",user_id=8,price=4.99,image="https://www.curiouscuisiniere.com/wp-content/uploads/2021/08/Marquesa-3.1-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=14)
    post45 = Post(name="Savory rosemary garlic -roast chicken Fluffy- lemon blueberry -pancakes",user_id=8,price=7.99,image="https://res.cloudinary.com/grow-me/image/fetch/c_fill,h_200,q_auto,w_200/f_auto,fl_lossy/https%3A%2F%2Fwww.willflyforfood.net%2Fwp-content%2Fuploads%2F2021%2F12%2Fperuvian-desserts-picarones-featured.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id="14")
    post46 = Post(name="Crispy pan-seared -salmon with dill cream -sauce Spicy shrimp veggie- stir-fry with sesame oil",user_id=8,price=1.99,image="https://chelsweets.com/wp-content/uploads/2020/10/recipe-card-5-scaled-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=14)
    post47 = Post(name="Creamy mushroom- thyme risotto- Tender slow-cooked -beef stew with root vegetables.",user_id=8,price=4.99,image="https://www.norinesnest.com/wp-content/uploads/2022/08/Peach-Pie-2022-6-1-scaled-e1661449690877-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=14)
    post48 = Post(name="Light crispy -tempura battered fish -Rich cheesy lasagna -with ground beef",user_id=9,price=9.99,image="https://www.esterkocht.com/wp-content/uploads/2018/12/How-to-make-orange-cream-dessert-with-orange-sauce.-Orangencreme-dessert-selber-machen-so-geht-es.-3-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=15)
    post49 = Post(name="Flavorful hearty- lentil soup Spicy -savory jambalaya with -sausage shrimp",user_id=9,price=3.99,image="https://thebigmansworld.com/wp-content/uploads/2021/10/pumpkin-dessert-recipes-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=15)
    post50 = Post(name="Creamy comforting -mac cheese Tender- juicy BBQ pulled -pork sandwiches",user_id=9,price=7.25,image="https://hips.hearstapps.com/delish/assets/cm/15/10/54fa065b88c70-buttermilk-panna-cotta-brandied-citrus-sauce-de.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=15)
    post51 = Post(name="Crunchy refreshing- coleslaw with a -tangy dressing Smooth -rich chocolate mousse cake",user_id=9,price=4.49,image="https://cookingchew.com/wp-content/uploads/2021/10/easy-party-desserts-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=15)
    post52 = Post(name="Juicy flavorful -marinated chicken skewers -Warm comforting -beef pot roast with vegetables",user_id=9,price=8.25,image="https://www.curiouscuisiniere.com/wp-content/uploads/2022/12/brigadeiro-brazilian-truffles-4.1-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=15)
    post53 = Post(name="Spicy Tofu Tacos - Crispy tofu flavorful spices, -fresh toppings with -Creamy Mushroom Risotto",user_id=10,price=2.25,image="https://bakeitwithlove.com/wp-content/uploads/2021/09/Pineapple-dump-cake-tall.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post54 = Post(name="Arborio rice cooked -in mushroom broth -finished- with parmesan",user_id=10,price=1.75,image="https://foodgressing.com/wp-content/uploads/2020/08/yan-bakery-vancouver-fresh-mango-cake-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post55 = Post(name="Sesame Crusted Ahi Tuna - Sesame seed crusted tuna- steak served with a soy ginger- glaze Lemon Herb Chicken ",user_id=10,price=8.25,image="https://resize.img.allw.mn/thumbs/00/surd8r8ca2rka63zdt9in_1080_1225.jpg?width=1200&height=1200",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post56 = Post(name="uicy chicken breast- marinated in lemon -herbs grilled- to perfection",user_id=10,price=4.49,image="https://media.istockphoto.com/id/463813283/photo/dark-chocolate-bar-on-rustic-wood-table.jpg?b=1&s=170667a&w=0&k=20&c=9ctRNlJ5lT50VakZJV9hn2bJUuRI7oRh226DlOWf-Vk=",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post57 = Post(name="Arborio rice cooked -in mushroom broth -finished- with parmesan",user_id=10,price=1.75,image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKboyKbpgJsUJhh9dWIkp5ClILdDD6sInEuA&usqp=CAU",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post58 = Post(name="Sesame Crusted Ahi Tuna - Sesame seed crusted tuna- steak served with a soy ginger- glaze Lemon Herb Chicken ",user_id=10,price=8.25,image="https://www.thebossykitchen.com/wp-content/uploads/2021/07/Sea-Salt-Chocolate-Fudge-square-photo0-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post59 = Post(name="uicy chicken breast- marinated in lemon -herbs grilled- to perfection",user_id=10,price=4.49,image="https://res.cloudinary.com/grow-me/image/fetch/c_fill,h_200,q_auto,w_200/f_auto,fl_lossy/https%3A%2F%2Fthebestblogrecipes.com%2Fwp-content%2Fuploads%2F2017%2F08%2FMint-Chocolate-Dessert-Recipes-1.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=16)
    post60 = Post(name='Purple Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=11, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://kirbiecravings.com/wp-content/uploads/2019/08/milk-pudding-200x200.jpg",shop_id=17)
    post61 = Post(name='Gree Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=11, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.fooodlove.com/images/uploads/recipes-square/_resized_thumb/Custard_and_Jelly_Dessert_01_square.jpg",shop_id=17)
    post62 = Post(name='Blue Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=11, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cEVY8K1p0N-3Xisu6xo7hMjxgMr1jCBf3QxONKG38ZYO_ijfs5hl_-SBHHz_a-JqRcY&usqp=CAU",shop_id=17)
    post63 = Post(name='Red Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=11, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://latinamommeals.com/wp-content/uploads/2019/07/Puerto-Rican-Cortado-Dulce-11-of-12-200x200.jpg",shop_id=17)
    post64 = Post(name='Yellow Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=12, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.mommysfabulousfinds.com/wp-content/uploads/2014/08/patriotic-dessert-cups-200x200.jpg",shop_id=18)
    post65 = Post(name='Orange Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=12, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://easymommeals.com/wp-content/uploads/2021/07/fresh-peach-dessert-recipe-200x200.jpg",shop_id=18)
    post66 = Post(name='Black Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=12, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.bigbearswife.com/wp-content/uploads/2018/03/Blue-Raspberry-Macarons-7-720x540.jpg",shop_id=18)
    post67 = Post(name='White Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=12, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://images.squarespace-cdn.com/content/v1/54151d7ee4b0a43a90459ae2/1600743669497-K2E8VHORQLKVTXV7FA0L/shutterstock_1115170646.jpg",shop_id=18)
    post68 = Post(name='Birria Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=12, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://www.taketwotapas.com/wp-content/uploads/2022/04/Louisiana-Stranger-Cake-Featured-Image-200x200.jpg.webp",shop_id=18)
    post69 = Post(name='Meat Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=13, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://ourtableforseven.com/wp-content/uploads/dark-chocolate-avocado-pudding-overhead-ourtableforseven.com_-200x200.jpg.webp",shop_id=19)
    post70 = Post(name='Lamb Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=13, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://diycandy.com/wp-content/uploads/2020/09/Small-dessert-mini-cheesecake-recipe.jpg",shop_id=19)
    post71 = Post(name='Steak Japanese Ramen Tonkatsu -Tasty Homemade Food - Grown in the Kitchen - Not From Hmart Trust', user_id=13, description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",price=1.99,image="https://minimalistbaker.com/wp-content/uploads/2021/09/MB-AppleButterDessertTamales-Pinterest-02-200x200.jpg",shop_id=19)
    post72 = Post(name="Zesty Tofu Stir-Fry with Peanuts -Cilantro Creamy Parmesan- Risotto with Roasted Vegetables",user_id=13,price=22.23,image="https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/04/06/FNK_Chocolate-Mousse_H_v2_4x3.jpg.rend.hgtvcom.616.462.suffix/1586200107816.jpeg",description="Juicy, seasoned grilled steak with a crispy crust and tender center, Fluffy, buttery croissants with layers of flaky pastry",shop_id=19)
    post73 = Post(name="Spicy Jalapeno -Lime Grilled Chicken -Savory Mushroom Leek Quiche -with a Whole Wheat Crust",user_id=13,price=12.21,image="https://www.withablast.net/wp-content/uploads/2015/01/StrawberryandCreamSconeCake-1.jpg.webp",description="Warm, comforting bowl of chicken noodle soup with tender vegetables, Creamy, rich alfredo pasta with garlic and parmesan",shop_id=19)
    post74 = Post(name="Sweet Sour Pineapple- Chicken Fried- RiceHearty Lentil -Kale Soup with Smoked Paprika",user_id=14,price=7.55,image="https://whereismyspoon.co/wp-content/uploads/2015/05/strawberry-meringue-dessert-4-200x200.jpg.webp",description="Spicy, tangy buffalo wings with a cool blue cheese dip, Tender, slow-cooked pulled pork with a smoky BBQ sauce",shop_id=20)
    post75 = Post(name="Crispy Sweet Potato -Black Bean Tacos with Avocado- CremaRich Creamy -Lobster Bisque with Sherry Thyme",user_id=14,price=6.99,image="https://borrowedbites.com/wp-content/uploads/2020/11/Square-Chocolate-Parfait-Mousse-Desserts.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=20)
    post76 = Post(name="Smoky BBQ Pulled Pork -Sandwiches with Coleslaw- Fresh Bright Watermelon -Feta Salad with Mint Lime",user_id=14,price=5.99,image="https://wholeandheavenlyoven.com/wp-content/uploads/2020/06/FI6-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=20)
    post77 = Post(name="Chunky Minestrone Soup -with Italian Sausage -Rosemary Crunchy Panko-Crusted Cod with",user_id=14,price=6.25,image="https://yummyaddiction.com/wp-content/uploads/2022/02/tropical-dessert-featured-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=20)
    post78 = Post(name="Hearty Lentil Kale Soup- with Smoked Paprika -Creamy Garlic -Parmesan Mashed Potatoes",user_id=14,price=9.99,image="https://wander-lush.org/wp-content/uploads/2022/07/Emily-Lush-traditional-Georgian-desserts-Kokorti.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=20)
    post79 = Post(name="Crispy Sweet Potato Black- Bean Tacos with Avocado Crema -Spicy Korean-style Fried Chicken with Gochujang Glaze",user_id=1,price=5.25,image="https://www.wholesomeyum.com/wp-content/uploads/2017/03/wholesomeyum-Keto-Cheesecake-Recipe-Low-Carb-Sugar-Free-Cheesecake.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=7)
    post80 = Post(name="Rich Creamy Lobster Bisque- with Sherry Thyme and- Hearty Beef Vegetable- Stew with Guinness Thyme",user_id=1,price=3.99,image="https://media.istockphoto.com/id/466724890/photo/healthy-homemade-carrot-cake.jpg?s=612x612&w=0&k=20&c=Qt89yzcMCq8awNO_EhJJwdBOp3yyJA2YYG01D7ZL3gA=",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=7)
    post81 = Post(name="Smoky BBQ Pulled Pork Sandwiches -with Coleslaw Crispy Air-Fried Eggplant Parmesan with- Mozzarella Basil",user_id=1,price=2.99,image="https://www.melskitchencafe.com/wp-content/uploads/2013/04/chocolate-cake-slice-jpg-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=7)
    post82 = Post(name="Fresh Bright Watermelon -Feta Salad with Mint -Lime Fresh Fruity Raspberry-Blueberry Cheesecake Bars",user_id=1,price=4.99,image="https://detoxinista.com/wp-content/uploads/2017/09/chocolate-birthday-cake.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=7)
    post83 = Post(name="Zesty Quinoa Salad with -Pomegranate Vinaigrette Juicy -Grilled Pineapple- with Lime Glaze",user_id=1,price=12.99,image="https://www.recipegirl.com/wp-content/uploads/2011/11/Red-Velvet-Cheesecake-Cake-1-1-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=7)
    post84 = Post(name="Creamy Garlic Mushroom -Linguine Chewy -Sesame Noodles with -Peanut Sauce",user_id=2,price=12.25,image="https://easydessertrecipes.com/wp-content/uploads/2021/02/red-velvet-cake-raspberry-cream-cheese-frosting-4-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post85 = Post(name="Spicy Tofu -Vegetable Stir Fry -Golden Fried Fish Tacos- with Cilantro Slaw",user_id=2,price=15.99,image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2SWcWK-8Ck5gQs69A3D6LxnZT7t6fRGHLBA&usqp=CAU",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post86 = Post(name="Crispy Fried Chicken -with Honey Mustard -Sauce Savory Roasted -Eggplant with Garlic Parmesan",user_id=2,price=5.99,image="https://spicedblog.com/wp-content/uploads/2015/05/Fresh-Blackberry-Cake1-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post87 = Post(name="Loaded Baked Potato -with Sour Cream Chives- Creamy Lemon- Herb Risotto",user_id=2,price=7.99,image="https://www.indulgewithmimi.com/wp-content/uploads/2018/10/matcha-green-tea-mille-pancake-crepe-cake-japanese-1-735x735.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post88 = Post(name="Flaky Croissant with Melted- Brie Prosciutto Crunchy- Fried Green Tomatoes- with Ranch Dressing",user_id=2,price=15.99,image="https://chelsweets.com/wp-content/uploads/2022/03/pulling-slice-out-of-matcha-cake-2-edited-scaled.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post89 = Post(name="Sizzling Grilled Steak- with Chimichurri -Hearty Vegetable -Bean Chili",user_id=2,price=19.99,image="https://static6.depositphotos.com/1010050/544/i/600/depositphotos_5449593-stock-photo-cream-cake.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=8)
    post90 = Post(name="Chilled Cucumber Dill -Soup Zesty- Lemon Herb- Grilled Chicken",user_id=3,price=11.99,image="https://www.theflavorbender.com/wp-content/uploads/2014/09/Simpsons-Doughnuts-4238-Copy-1-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post91 = Post(name="Smoky BBQ -Pulled Pork -Sandwich Smoky- Bacon Wrapped Meatloaf",user_id=3,price=9.99,image="https://bakerish.com/wp-content/uploads/2019/03/LEMON-DONUTS1-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post92 = Post(name="Warm Apple- Cinnamon Oatmeal- Warm Spiced- Apple Cider",user_id=3,price=16.99,image="https://bakeitwithlove.com/wp-content/uploads/2022/08/baked-donuts-sq-500x500.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post93 = Post(name="Tender beef brisket- with smoky BBQ -sauce Creamy pumpkin- risotto with sage parmesan",user_id=3,price=29.99,image="https://chocolatecoveredkatie.com/wp-content/uploads/2013/02/donuts-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post94 = Post(name="Spicy black -bean sweet potato- enchiladas Juicy grilled -pork chops with apple chutney",user_id=3,price=4.99,image="https://cleanplatemama.com/wp-content/uploads/2022/01/chocolate-covered-donut-thumbnail-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post95 = Post(name="Savory rosemary garlic -roast chicken Fluffy- lemon blueberry -pancakes",user_id=3,price=7.99,image="https://www.bostongirlbakes.com/wp-content/uploads/2021/09/IMG_4423-scaled-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=9)
    post96 = Post(name="Crispy pan-seared -salmon with dill cream -sauce Spicy shrimp veggie- stir-fry with sesame oil",user_id=4,price=1.99,image="https://www.norinesnest.com/wp-content/uploads/2021/02/Peach-Fritters-2020-4-1-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=10)
    post97 = Post(name="Creamy mushroom- thyme risotto- Tender slow-cooked -beef stew with root vegetables.",user_id=4,price=4.99,image="https://www.norinesnest.com/wp-content/uploads/2022/08/Peach-Pie-2022-6-1-scaled-e1661449690877-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=10)
    post98 = Post(name="Light crispy -tempura battered fish -Rich cheesy lasagna -with ground beef",user_id=4,price=9.99,image="https://bakingmischief.com/wp-content/uploads/2016/11/nanowrimo-snacks-bakingmischief.com-strawberry-glazed-sencha-green-tea-doughnuts-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=10)
    post99 = Post(name="Flavorful hearty- lentil soup Spicy -savory jambalaya with -sausage shrimp",user_id=4,price=3.99,image="https://bakerish.com/wp-content/uploads/2020/03/CHOCOLATE-DONUTS-3-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=10)
    post100 = Post(name="Chilled Cucumber Dill -Soup Zesty- Lemon Herb- Grilled Chicken",user_id=4,price=11.99,image="https://www.thecountrycook.net/wp-content/uploads/2022/01/thumbnail-Red-Velvet-Donuts-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=10)
    post101 = Post(name="Smoky BBQ -Pulled Pork -Sandwich Smoky- Bacon Wrapped Meatloaf",user_id=5,price=9.99,image="https://www.kitchenathoskins.com/wp-content/uploads/2018/05/super-soft-glazed-doughnuts-8-yum.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post102 = Post(name="Warm Apple- Cinnamon Oatmeal- Warm Spiced- Apple Cider",user_id=5,price=16.99,image="https://buildyourbite.com/wp-content/uploads/2018/09/strawberry-banana-smoothie-featured-735x735.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post103 = Post(name="Tender beef brisket- with smoky BBQ -sauce Creamy pumpkin- risotto with sage parmesan",user_id=5,price=29.99,image="https://www.myketoplanner.com/images/Recipes/Recipe32_Ketocal%20Strawberry%20Smoohie.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post104 = Post(name="Spicy black -bean sweet potato- enchiladas Juicy grilled -pork chops with apple chutney",user_id=5,price=4.99,image="https://morethanmeatandpotatoes.com/wp-content/uploads/2022/04/Blueberry-Smoothie-Featured-Image-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post105 = Post(name="Savory rosemary garlic -roast chicken Fluffy- lemon blueberry -pancakes",user_id=5,price=7.99,image="https://www.runningtothekitchen.com/wp-content/uploads/2019/01/pineapple-kiwi-mint-smoothie-200x200-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post106 = Post(name="Crispy pan-seared -salmon with dill cream -sauce Spicy shrimp veggie- stir-fry with sesame oil",user_id=5,price=1.99,image="https://www.acedarspoon.com/wp-content/uploads/2018/04/Coconut-Carrot-Smoothie-2-225x300-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post107 = Post(name="Creamy mushroom- thyme risotto- Tender slow-cooked -beef stew with root vegetables.",user_id=5,price=4.99,image="https://www.twopurplefigs.com/wp-content/uploads/2021/01/Tropical-Smoothie-18-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id="14")
    post108 = Post(name="Light crispy -tempura battered fish -Rich cheesy lasagna -with ground beef",user_id=5,price=9.99,image="https://lianaskitchen.co.uk/wp-content/uploads/2016/09/Mango-Smoothie-e1474539440172-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=11)
    post109 = Post(name="Flavorful hearty- lentil soup Spicy -savory jambalaya with -sausage shrimp",user_id=6,price=3.99,image="https://www.ourhappymess.com/wp-content/uploads/2019/01/Triple-Berry-Greek-Yogurt-Smoothies-3-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post110 = Post(name="Chilled Cucumber Dill -Soup Zesty- Lemon Herb- Grilled Chicken",user_id=6,price=11.99,image="https://www.simplisticallyliving.com/wp-content/uploads/2018/12/Red-Velvet-Heart-Crinkle-Cookies-featured-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post111 = Post(name="Smoky BBQ -Pulled Pork -Sandwich Smoky- Bacon Wrapped Meatloaf",user_id=6,price=9.99,image="https://images.squarespace-cdn.com/content/v1/62ec39cc230c972456f6116d/1666140333667-8MXXOJYTH26DF79FDK8W/28575754_1885740288317590_588813335314046138_n.jpg?format=1500w",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post112 = Post(name="Warm Apple- Cinnamon Oatmeal- Warm Spiced- Apple Cider",user_id=6,price=16.99,image="https://foodgressing.com/wp-content/uploads/2017/08/mango-korean-shaved-dessert-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post113 = Post(name="Tender beef brisket- with smoky BBQ -sauce Creamy pumpkin- risotto with sage parmesan",user_id=6,price=29.99,image="https://sucrecafe.com/wp-content/uploads/2020/01/img_9826-e1580256719133-1280x1280.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post114 = Post(name="Spicy black -bean sweet potato- enchiladas Juicy grilled -pork chops with apple chutney",user_id=6,price=4.99,image="https://www.curiouscuisiniere.com/wp-content/uploads/2021/08/Marquesa-3.1-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post115 = Post(name="Savory rosemary garlic -roast chicken Fluffy- lemon blueberry -pancakes",user_id=6,price=7.99,image="https://cookwithrenu.com/wp-content/uploads/2021/11/Coconut-Oil-Vegan-Chocolate-Chip-Cookies_Featured-Image-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post116 = Post(name="Crispy pan-seared -salmon with dill cream -sauce Spicy shrimp veggie- stir-fry with sesame oil",user_id=6,price=1.99,image="https://www.lecremedelacrumb.com/wp-content/uploads/2021/12/santas-cookies-1sm-5-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post117 = Post(name="Creamy mushroom- thyme risotto- Tender slow-cooked -beef stew with root vegetables.",user_id=6,price=4.99,image="https://www.thefrostedkitchen.com/wp-content/uploads/2021/10/Chocolate-chip-cookies-with-crisco-2-scaled-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=12)
    post118 = Post(name="Light crispy -tempura battered fish -Rich cheesy lasagna -with ground beef",user_id=12,price=9.99,image="https://www.curiouscuisiniere.com/wp-content/uploads/2022/08/alfajores-marplatenses-8.crop_-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=18)
    post119 = Post(name="Flavorful hearty- lentil soup Spicy -savory jambalaya with -sausage shrimp",user_id=12,price=3.99,image="https://www.melskitchencafe.com/wp-content/uploads/2013/04/Peanut-Blossom-Cookies-Plate-jpg-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=18)
    post120 = Post(name="Warm Apple- Cinnamon Oatmeal- Warm Spiced- Apple Cider",user_id=12,price=16.99,image="https://numstheword.com/wp-content/uploads/2022/11/caramel-peanut-butter-and-pretzel-cookies-200x200.jpg.webp",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=18)
    post121 = Post(name="Tender beef brisket- with smoky BBQ -sauce Creamy pumpkin- risotto with sage parmesan",user_id=12,price=29.99,image="https://bakeorbreak.com/wp-content/uploads/2022/12/Red-Velvet-Cookie-Sandwiches-50-200x200.jpg",description="Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good Very good ",shop_id=18)

    db.session.add(post1)
    db.session.add(post2)
    db.session.add(post3)
    db.session.add(post4)
    db.session.add(post5)
    db.session.add(post6)
    db.session.add(post7)
    db.session.add(post8)
    db.session.add(post9)
    db.session.add(post10)
    db.session.add(post11)
    db.session.add(post12)
    db.session.add(post13)
    db.session.add(post14)
    db.session.add(post15)
    db.session.add(post16)
    db.session.add(post17)
    db.session.add(post18)
    db.session.add(post19)
    db.session.add(post20)
    db.session.add(post21)
    db.session.add(post22)
    db.session.add(post23)
    db.session.add(post24)
    db.session.add(post25)
    db.session.add(post26)
    db.session.add(post27)
    db.session.add(post28)
    db.session.add(post29)
    db.session.add(post30)
    db.session.add(post31)
    db.session.add(post32)
    db.session.add(post33)
    db.session.add(post34)
    db.session.add(post35)
    db.session.add(post36)
    db.session.add(post37)
    db.session.add(post38)
    db.session.add(post39)
    db.session.add(post40)
    db.session.add(post41)
    db.session.add(post42)
    db.session.add(post43)
    db.session.add(post44)
    db.session.add(post45)
    db.session.add(post46)
    db.session.add(post47)
    db.session.add(post48)
    db.session.add(post49)
    db.session.add(post50)
    db.session.add(post51)
    db.session.add(post52)
    db.session.add(post53)
    db.session.add(post54)
    db.session.add(post55)
    db.session.add(post56)
    db.session.add(post57)
    db.session.add(post58)
    db.session.add(post59)
    db.session.add(post60)
    db.session.add(post61)
    db.session.add(post62)
    db.session.add(post63)
    db.session.add(post64)
    db.session.add(post65)
    db.session.add(post66)
    db.session.add(post67)
    db.session.add(post68)
    db.session.add(post69)
    db.session.add(post70)
    db.session.add(post71)
    db.session.add(post72)
    db.session.add(post73)
    db.session.add(post74)
    db.session.add(post75)
    db.session.add(post76)
    db.session.add(post77)
    db.session.add(post78)
    db.session.add(post79)
    db.session.add(post80)
    db.session.add(post81)
    db.session.add(post82)
    db.session.add(post83)
    db.session.add(post84)
    db.session.add(post85)
    db.session.add(post86)
    db.session.add(post87)
    db.session.add(post88)
    db.session.add(post89)
    db.session.add(post90)
    db.session.add(post91)
    db.session.add(post92)
    db.session.add(post93)
    db.session.add(post94)
    db.session.add(post95)
    db.session.add(post96)
    db.session.add(post97)
    db.session.add(post98)
    db.session.add(post99)
    db.session.add(post100)
    db.session.add(post101)
    db.session.add(post102)
    db.session.add(post103)
    db.session.add(post104)
    db.session.add(post105)

    db.session.add(post106)
    db.session.add(post107)
    db.session.add(post108)
    db.session.add(post109)
    db.session.add(post110)
    db.session.add(post111)
    db.session.add(post112)
    db.session.add(post113)
    db.session.add(post114)
    db.session.add(post115)
    db.session.add(post116)
    db.session.add(post117)
    db.session.add(post118)
    db.session.add(post119)
    db.session.add(post120)
    db.session.add(post121)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_posts():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM posts")
        
    db.session.commit()